const modeLabels = {
  ask: 'Explain',
  plan: 'Plan',
  agent: 'Edit',
  builder: 'Build',
  ship: 'Ship',
};

const reasoningLabels = {
  low: 'Low',
  medium: 'Medium',
  high: 'High',
};

const permissionLabels = {
  read: 'Read Only',
  ask: 'Ask Before Write',
  terminal: 'Auto Write, Ask Terminal',
  workspace: 'Workspace Auto',
  full: 'Full Auto',
};

const nvidiaModels = [
  { id: 'nvidia/nemotron-3-nano-30b-a3b', label: 'Nemotron 3 Nano 30B', description: 'Default coding and agent model' },
  { id: 'nvidia/llama-3.1-nemotron-nano-8b-v1', label: 'Llama Nemotron Nano 8B', description: 'Fast edits and explanations' },
  { id: 'moonshotai/kimi-k2.6', label: 'Kimi K2.6', description: 'Large coding and agent model; can be slower to start' },
  { id: 'minimaxai/minimax-m2.7', label: 'MiniMax M2.7', description: 'Large coding and reasoning model; can be slower to start' },
  { id: 'qwen/qwen3-coder-480b-a35b-instruct', label: 'Qwen3 Coder 480B', description: 'Large NVIDIA NIM coding model' },
  { id: 'qwen/qwen3-next-80b-a3b-instruct', label: 'Qwen3 Next 80B', description: 'General coding and instruction model' },
  { id: 'qwen/qwen3-next-80b-a3b-thinking', label: 'Qwen3 Next 80B Thinking', description: 'Reasoning-heavy NVIDIA NIM model' },
  { id: 'bigcode/starcoder2-15b', label: 'StarCoder2 15B', description: 'Code generation model' },
  { id: 'mistralai/codestral-22b-instruct-v0.1', label: 'Codestral 22B', description: 'Code generation and editing model' },
  { id: 'ibm/granite-34b-code-instruct', label: 'Granite Code 34B', description: 'Code instruction model' },
  { id: 'ibm/granite-8b-code-instruct', label: 'Granite Code 8B', description: 'Fast code instruction model' },
  { id: 'google/codegemma-7b', label: 'CodeGemma 7B', description: 'Fast code generation model' },
  { id: 'meta/codellama-70b', label: 'CodeLlama 70B', description: 'Large code generation model' },
  { id: 'deepseek-ai/deepseek-coder-6.7b-instruct', label: 'DeepSeek Coder 6.7B', description: 'Fast code generation model' },
  { id: 'deepseek-ai/deepseek-v4-flash', label: 'DeepSeek V4 Flash', description: 'Fast coding and agent tasks' },
  { id: 'deepseek-ai/deepseek-v4-pro', label: 'DeepSeek V4 Pro', description: 'Larger DeepSeek reasoning and coding model' },
  { id: 'nvidia/llama-3.1-nemotron-51b-instruct', label: 'Llama Nemotron 51B', description: 'Larger coding/general reasoning model' },
];

const editableModes = new Set(['agent', 'builder', 'ship']);
const ignoredGlob = '{**/node_modules/**,**/.git/**,**/dist/**,**/build/**,**/out/**,**/.next/**,**/.turbo/**,**/coverage/**}';
const maxContextBytes = 12000;
const maxAttachmentBytes = 2_000_000;
const defaultNimTimeoutMs = 45000;
const agentMaxSteps = 12;
const agentObservationBytes = 9000;
const agentSearchFileLimit = 240;
const agentSearchMatchLimit = 30;
const backgroundAgentMaxAttempts = 3;

const agentTools = [
  { action: 'list_files', args: '{"limit":120}', description: 'List workspace files while respecting ignored build/dependency folders.' },
  { action: 'read_file', args: '{"filePath":"relative/path"}', description: 'Read a workspace file before editing it.' },
  { action: 'search', args: '{"query":"text","limit":20}', description: 'Search workspace text across source files.' },
  { action: 'inspect_package_scripts', args: '{"filePath":"package.json"}', description: 'Read package manager scripts and dependencies to choose targeted install/build/test/dev commands.' },
  { action: 'production_profile', args: '{}', description: 'Detect framework, package manager, build output, verification scripts, deploy config, and recommended production shipping commands.' },
  { action: 'git_status', args: '{}', description: 'Inspect current git status for changed files before deciding edits or merge risk.' },
  { action: 'get_diagnostics', args: '{"filePath":"optional/relative/path"}', description: 'Read current VS Code diagnostics for the workspace or one file.' },
  { action: 'shadcn_info', args: '{}', description: 'Inspect shadcn/ui configuration when a project has components.json.' },
  { action: 'preview_status', args: '{}', description: 'Read the latest preview URL and verification result known to Neura.' },
  { action: 'semantic_search', args: '{"query":"symbol or concept","limit":20}', description: 'Search the local semantic index for symbols and relevant files.' },
  { action: 'browser_verify', args: '{"url":"http://localhost:3000"}', description: 'Run headless browser verification with screenshot when a local browser is installed.' },
  { action: 'browser_agent', args: '{"url":"http://localhost:3000","steps":[{"action":"click","selector":"button"},{"action":"type","selector":"input","text":"hello"},{"action":"scroll","y":600}]}', description: 'Drive a local preview through a browser agent: capture DOM, screenshots, console/runtime errors, click/type/scroll actions, and a replay artifact.' },
  { action: 'run_command', args: '{"command":"npm test","purpose":"why this is safe and useful"}', description: 'Run a verification command only when Full Auto permission is enabled and the command passes safety guardrails; otherwise the agent must propose it at finish.' },
  { action: 'tool_batch', args: '{"actions":[{"action":"list_files","args":{"limit":120}},{"action":"git_status","args":{}}]}', description: 'Run multiple observation tools in one step when they are independent. Do not include mutating commands in a batch.' },
];

const swarmRoles = [
  {
    id: 'orchestrator',
    label: 'Orchestrator',
    squad: 'Command',
    default: true,
    writes: false,
    dependencies: [],
    mission: 'Own the mission breakdown, dependency order, merge risks, and final coordination notes.',
    focus: ['Architecture decomposition', 'role assignments', 'dependency risks', 'merge strategy'],
    deliverables: ['mission summary', 'ordered work plan', 'risk list', 'handoff notes for other agents'],
    ownership: [],
  },
  {
    id: 'planner',
    label: 'Planner',
    squad: 'Command',
    default: true,
    writes: false,
    dependencies: ['orchestrator'],
    mission: 'Create a production implementation plan, task graph, open questions, and acceptance criteria.',
    focus: ['implementation plan', 'task graph', 'acceptance criteria', 'unknowns'],
    deliverables: ['step-by-step plan', 'test plan', 'blocked questions if any'],
    ownership: [],
  },
  {
    id: 'context',
    label: 'Context',
    squad: 'Command',
    default: true,
    writes: false,
    dependencies: ['orchestrator'],
    mission: 'Map the codebase, relevant files, symbols, contracts, and risks before implementation starts.',
    focus: ['codebase map', 'file ownership', 'public contracts', 'dependency graph'],
    deliverables: ['relevant files', 'architecture notes', 'integration constraints'],
    ownership: [],
  },
  {
    id: 'frontend',
    label: 'Frontend',
    squad: 'Build',
    default: true,
    writes: true,
    dependencies: ['planner', 'context'],
    mission: 'Implement UI, layout, styling, accessibility, frontend state, and browser-facing behavior.',
    focus: ['components', 'views', 'styling', 'responsive behavior', 'frontend errors'],
    deliverables: ['targeted frontend edits', 'UI verification command', 'changed component summary'],
    ownership: ['src/**', 'app/**', 'pages/**', 'components/**', 'styles/**', 'public/**', '**/*.html', '**/*.css', '**/*.scss', '**/*.jsx', '**/*.tsx'],
  },
  {
    id: 'backend',
    label: 'Backend',
    squad: 'Build',
    default: true,
    writes: true,
    dependencies: ['planner', 'context'],
    mission: 'Implement APIs, services, server logic, auth boundaries, persistence adapters, and backend tests.',
    focus: ['services', 'IPC/API contracts', 'server behavior', 'auth and validation', 'backend tests'],
    deliverables: ['targeted backend edits', 'contract notes', 'backend verification command'],
    ownership: ['server/**', 'api/**', 'src/main/**', 'services/**', 'routes/**', 'ipc/**', '**/*.ts', '**/*.js'],
  },
  {
    id: 'data-state',
    label: 'Data/State',
    squad: 'Build',
    default: false,
    writes: true,
    dependencies: ['planner', 'context'],
    mission: 'Implement schema, migrations, local storage, cache, app state, and data consistency behavior.',
    focus: ['schema', 'migrations', 'state stores', 'cache invalidation', 'data integrity'],
    deliverables: ['state/data edits', 'migration or persistence notes', 'data verification command'],
    ownership: ['schema/**', 'migrations/**', 'db/**', 'store/**', 'state/**', 'data/**', '**/*.sql', '**/*.json'],
  },
  {
    id: 'integration',
    label: 'Integration',
    squad: 'Build',
    default: true,
    writes: true,
    dependencies: ['frontend', 'backend', 'data-state'],
    mission: 'Wire frontend/backend contracts, routes, IPC, extension APIs, environment settings, and end-to-end flow.',
    focus: ['interfaces', 'route wiring', 'IPC/API glue', 'environment config', 'end-to-end flow'],
    deliverables: ['integration edits', 'compatibility notes', 'end-to-end verification command'],
    ownership: ['src/shared/**', 'src/main/ipcRoutes/**', 'src/renderer/**', 'extensions/**', 'package.json', 'tsconfig*.json', 'vite.config.*'],
  },
  {
    id: 'qa',
    label: 'QA/Test',
    squad: 'Quality',
    default: true,
    writes: true,
    dependencies: ['integration', 'browser'],
    mission: 'Discover and run targeted tests, lint, typecheck, build, and repair obvious verification failures.',
    focus: ['test discovery', 'targeted checks', 'lint/type errors', 'build failures', 'repair loop'],
    deliverables: ['test fixes if needed', 'verification commands', 'failure evidence'],
    ownership: ['test/**', 'tests/**', '__tests__/**', 'spec/**', '**/*.test.*', '**/*.spec.*', 'playwright.config.*', 'vitest.config.*'],
  },
  {
    id: 'reviewer',
    label: 'Review/Security',
    squad: 'Quality',
    default: true,
    writes: false,
    dependencies: ['qa'],
    mission: 'Review final diffs for regressions, unsafe commands, secrets, security issues, and missing tests.',
    focus: ['diff review', 'security review', 'regression risk', 'missing tests', 'merge blockers'],
    deliverables: ['review findings', 'blockers', 'merge recommendation'],
    ownership: [],
  },
  {
    id: 'browser',
    label: 'Browser Agent',
    squad: 'Quality',
    default: true,
    writes: false,
    dependencies: ['integration'],
    mission: 'Interact with the running local app through Chrome/Edge DevTools, capture DOM, screenshots, console errors, and browser replay evidence.',
    focus: ['DOM capture', 'console/runtime errors', 'click/type/scroll flows', 'visual smoke checks', 'preview screenshots', 'browser replay artifacts'],
    deliverables: ['browser agent report', 'DOM snapshot', 'screenshot paths', 'console/runtime issue list', 'interaction recording path'],
    ownership: [],
  },
  {
    id: 'ship',
    label: 'Ship',
    squad: 'Release',
    default: true,
    writes: true,
    dependencies: ['qa', 'reviewer'],
    mission: 'Prepare release readiness: package/build checks, changelog notes, proof bundle, and shipping checklist.',
    focus: ['release checklist', 'packaging', 'proof bundle', 'final verification', 'ship notes'],
    deliverables: ['ship checklist', 'packaging command', 'proof-of-work summary'],
    ownership: ['docs/**', 'CHANGELOG*', 'README*', 'package.json', 'scripts/**', 'build/**', 'installer/**'],
  },
];

const swarmRoleById = Object.fromEntries(swarmRoles.map((role) => [role.id, role]));

module.exports = {
  modeLabels,
  reasoningLabels,
  permissionLabels,
  nvidiaModels,
  editableModes,
  ignoredGlob,
  maxContextBytes,
  maxAttachmentBytes,
  defaultNimTimeoutMs,
  agentMaxSteps,
  agentObservationBytes,
  agentSearchFileLimit,
  agentSearchMatchLimit,
  backgroundAgentMaxAttempts,
  agentTools,
  swarmRoles,
  swarmRoleById,
};
