packages:
  - 'apps/*'
  - 'apps/agent-tars/src/*'
  - 'apps/neura/src/*'
  - 'packages/neura-desktop/**'
  - 'packages/agent-infra/**'
  - '!packages/agent-infra/create-new-mcp/template-*'
  - 'packages/common/*'
  - '!packages/neura-desktop/visualizer'
