import {
  Hand,
  Keyboard,
  Type,
  MousePointerClick,
  ScrollText,
  AlertCircle,
  CheckSquare,
  RotateCcw,
  Hourglass,
  Camera,
  Globe,
  Terminal,
  FileText,
  FolderPlus,
  Archive,
  PackageOpen,
  Table,
  Presentation,
  FileType,
  PlayCircle,
  StopCircle,
  List,
  Activity,
  Download,
  Save,
  SearchCode,
  ClipboardList,
  CheckCircle2,
  Image,
  Mic,
  Video,
  Plug,
} from 'lucide-react';

export const ActionIconMap = {
  scroll: ScrollText,
  drag: Hand,
  hotkey: Keyboard,
  type: Type,
  type_element: Type,
  run_command: Terminal,
  read_file: FileText,
  write_file: FileText,
  edit_file: FileText,
  list_dir: List,
  file_info: SearchCode,
  create_folder: FolderPlus,
  copy_file: FileText,
  move_file: FileText,
  zip_files: Archive,
  unzip_file: PackageOpen,
  create_docx: FileText,
  create_pdf: FileType,
  create_xlsx: Table,
  create_pptx: Presentation,
  start_process: PlayCircle,
  read_process: Terminal,
  stop_process: StopCircle,
  list_processes: List,
  create_monitor: Activity,
  list_monitors: List,
  stop_monitor: StopCircle,
  create_website_project: Globe,
  start_website_preview: PlayCircle,
  export_website_project: Archive,
  generate_image: Image,
  transcribe_audio: Mic,
  synthesize_speech: Mic,
  analyze_video: Video,
  list_connectors: Plug,
  connector_slack_post: Plug,
  connector_drive_export: Plug,
  extract_page: SearchCode,
  download_url: Download,
  save_page_screenshot: Save,
  task_started: PlayCircle,
  plan_updated: ClipboardList,
  step_started: Activity,
  step_completed: CheckCircle2,
  step_failed: AlertCircle,
  validation_completed: CheckSquare,
  task_completed: CheckCircle2,
  navigate: Globe,
  navigate_back: RotateCcw,
  click_element: MousePointerClick,
  click: MousePointerClick,
  left_double: MousePointerClick,
  right_single: MousePointerClick,
  error_env: AlertCircle,
  finished: CheckSquare,
  call_user: RotateCcw,
  wait: Hourglass,
  screenshot: Camera,
};
